<?php
/*
These socket summary tables aggregate timer and byte count information for socket operations:

socket_summary_by_event_name: Aggregate timer and byte count statistics generated by the wait/io/socket/* instruments for all socket I/O operations, per socket instrument.

socket_summary_by_instance: Aggregate timer and byte count statistics generated by the wait/io/socket/* instruments for all socket I/O operations, per socket instance.
When a connection terminates, the row in socket_summary_by_instance corresponding to it is deleted.

The socket summary tables do not aggregate waits generated by idle events while sockets are waiting for the next request from the client. For idle event aggregations,
use the wait-event summary tables; see Section 26.12.18.1, “Wait Event Summary Tables”.

这些套接字汇总表聚合了套接字操作的计时器和字节计数信息:

socket_summary_by_event_name:聚合由wait/io/套接字/*工具为每个套接字工具生成的所有套接字I/O操作的计时器和字节计数统计。

socket_summary_by_instance:聚合由wait/io/socket/*工具为每个socket实例生成的所有socket I/O操作的计时器和字节计数统计信息。当连接终止时，socket_summary_by_instance中与之对应的行被删除。

套接字在等待客户机的下一个请求时，套接字汇总表不会聚合空闲事件生成的等待。对于空闲事件聚合，使用等待事件汇总表;参见第26.12.18.1节“等待事件汇总表”。
*/

return [
	//Socket waits and I/O per event name
	//https://dev.mysql.com/doc/refman/8.0/en/socket-summary-tables.html
	'tableName' => 'socket_summary_by_event_name',
	'tableDesc' => '依据事件名划分的socket汇总',
	'fields' => [
		'EVENT_NAME' => [
			//
			'name' => '事件名',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'COUNT_STAR' => [
			//The number of summarized events. This value includes all events, whether timed or nontimed.
			'name' => '事件的数目',
			'desc' => '汇总事件的数目。此值包括所有定时或非定时事件。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_WAIT' => [
			//The total wait time of the summarized timed events. This value is calculated only for timed events because nontimed events have a wait time of NULL. The same is true for the other xxx_TIMER_WAIT values.
			'name' => '事件的总等待时间',
			'desc' => '汇总的定时事件的总等待时间。此值仅针对定时事件计算，因为非定时事件的等待时间为NULL。对于其他的xxx_TIMER_WAIT值也是如此。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'MIN_TIMER_WAIT' => [
			//The minimum wait time of the summarized timed events.
			'name' => '事件的最短等待时间',
			'desc' => '摘要定时事件的最短等待时间。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'AVG_TIMER_WAIT' => [
			//The average wait time of the summarized timed events.
			'name' => '事件的平均等待时间',
			'desc' => '摘要定时事件的平均等待时间。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'MAX_TIMER_WAIT' => [
			//The maximum wait time of the summarized timed events.
			'name' => '事件的最大等待时间',
			'desc' => '摘要定时事件的最大等待时间。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'COUNT_READ' => [
			//These columns aggregate all receive operations (RECV, RECVFROM, and RECVMSG).
			'name' => '接收次数总计',
			'desc' => '这些列汇总了所有接收操作（RECV，RECVFROM和RECVMSG）。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_READ' => [
			//
			'name' => '接收耗时总计',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'MIN_TIMER_READ' => [
			//
			'name' => '接收最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'AVG_TIMER_READ' => [
			//
			'name' => '接收平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'MAX_TIMER_READ' => [
			//
			'name' => '接收最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'SUM_NUMBER_OF_BYTES_READ' => [
			//
			'name' => '共接收字节',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'COUNT_WRITE' => [
			//These columns aggregate all send operations (SEND, SENDTO, and SENDMSG).
			'name' => '发送次数总计',
			'desc' => '这些列汇总了所有发送操作（SEND，SENDTO和SENDMSG）。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_WRITE' => [
			//
			'name' => '发送耗时总计',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'MIN_TIMER_WRITE' => [
			//
			'name' => '发送最低耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'AVG_TIMER_WRITE' => [
			//
			'name' => '发送平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'MAX_TIMER_WRITE' => [
			//
			'name' => '发送最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'SUM_NUMBER_OF_BYTES_WRITE' => [
			//
			'name' => '总发送字节',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'COUNT_MISC' => [
			//These columns aggregate all other socket operations, such as CONNECT, LISTEN, ACCEPT, CLOSE, and SHUTDOWN. There are no byte counts for these operations.
			'name' => '其他操作次数总计',
			'desc' => '这些列聚合了所有其他套接字操作，如连接、侦听、接受、关闭和关闭。这些操作没有字节计数。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_MISC' => [
			//
			'name' => '其他操作耗时总计',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_MISC'
		],
		'MIN_TIMER_MISC' => [
			//
			'name' => '其他操作最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_MISC'
		],
		'AVG_TIMER_MISC' => [
			//
			'name' => '其他操作平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_MISC'
		],
		'MAX_TIMER_MISC' => [
			//
			'name' => '其他操作最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_MISC'
		],
	]
];
