<?php
/*
The table_io_waits_summary_by_table table aggregates all table I/O wait events, as generated by the wait/io/table/sql/handler instrument. The grouping is by table.

The table_io_waits_summary_by_table table has these grouping columns to indicate how the table aggregates events: OBJECT_TYPE, OBJECT_SCHEMA, and OBJECT_NAME. 
These columns have the same meaning as in the events_waits_current table. They identify the table to which the row applies.

table_io_waits_summary_by_table has the following summary columns containing aggregated values. As indicated in the column descriptions, 
some columns are more general and have values that are the same as the sum of the values of more fine-grained columns. For example, 
columns that aggregate all writes hold the sum of the corresponding columns that aggregate inserts, updates, and deletes. In this way, aggregations at higher levels are available directly without the

table_io_waits_summary_by_table表聚合了所有由wait/io/table/sql/handler工具生成的表I/O等待事件。分组是按表进行的。

table_io_waits_summary_by_table表有这些分组列来指示表如何聚合事件:OBJECT_TYPE、OBJECT_SCHEMA和OBJECT_NAME。这些列的含义与events_waits_current表中的相同。它们标识行应用到的表。

table_io_waits_summary_by_table有以下包含聚合值的摘要列。如列描述中所示，有些列更通用，其值与更细粒度的列的值之和相同。
例如，聚合所有写操作的列包含聚合插入、更新和删除操作的对应列的总和。通过这种方式，可以直接使用较高级别的聚合，而不需要
*/

return [
	//Table I/O waits per table
	//https://dev.mysql.com/doc/refman/8.0/en/table-waits-summary-tables.html#performance-schema-table-io-waits-summary-by-table-table
	'tableName' => 'table_io_waits_summary_by_table',
	'tableDesc' => '根据表汇总的表I/O等待事件',
	'fields' => [
		'OBJECT_TYPE' => [
			//
			'name' => 'OBJECT_TYPE',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'OBJECT_SCHEMA' => [
			//
			'name' => 'OBJECT_SCHEMA',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'OBJECT_NAME' => [
			//
			'name' => 'OBJECT_NAME',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'COUNT_STAR' => [
			//These columns aggregate all I/O operations. They are the same as the sum of the corresponding xxx_READ and xxx_WRITE columns.
			'name' => 'IO操作总数',
			'desc' => '这些列汇总了所有I / O操作。它们与相应的xxx_READ和xxx_WRITE列的总和相同。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_WAIT' => [
			//
			'name' => 'IO操作总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_STAR'
		],
		'MIN_TIMER_WAIT' => [
			//
			'name' => 'IO操作最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_STAR'
		],
		'AVG_TIMER_WAIT' => [
			//
			'name' => 'IO操作平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_STAR'
		],
		'MAX_TIMER_WAIT' => [
			//
			'name' => 'IO操作最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_STAR'
		],
		'COUNT_READ' => [
			//These columns aggregate all read-lock operations. They are the same as the sum of the corresponding xxx_READ_NORMAL, xxx_READ_WITH_SHARED_LOCKS, xxx_READ_HIGH_PRIORITY, and xxx_READ_NO_INSERT columns.
			'name' => '读总次数',
			'desc' => '这些列聚合了所有读锁操作。它们等于对应的xxx_READ_NORMAL、xxx_READ_WITH_SHARED_LOCKS、xxx_READ_HIGH_PRIORITY和xxx_READ_NO_INSERT列的和。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_READ' => [
			//
			'name' => '读总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'MIN_TIMER_READ' => [
			//
			'name' => '读最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'AVG_TIMER_READ' => [
			//
			'name' => '读平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'MAX_TIMER_READ' => [
			//
			'name' => '读最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_READ'
		],
		'COUNT_WRITE' => [
			//These columns aggregate all write-lock operations. They are the same as the sum of the corresponding xxx_WRITE_ALLOW_WRITE, xxx_WRITE_CONCURRENT_INSERT, xxx_WRITE_LOW_PRIORITY, and xxx_WRITE_NORMAL columns.
			'name' => '写总次数',
			'desc' => '这些列聚合了所有写锁操作。它们与对应的xxx_WRITE_ALLOW_WRITE、xxx_WRITE_CONCURRENT_INSERT、xxx_WRITE_LOW_PRIORITY和xxx_WRITE_NORMAL列的和相同。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'SUM_TIMER_WRITE' => [
			//
			'name' => '写总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'MIN_TIMER_WRITE' => [
			//
			'name' => '写最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'AVG_TIMER_WRITE' => [
			//
			'name' => '写平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'MAX_TIMER_WRITE' => [
			//
			'name' => '写最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_WRITE'
		],
		'COUNT_FETCH' => [
			//These columns aggregate all fetch operations.
			'name' => '获取操作总数',
			'desc' => '这些列聚合了所有的获取操作。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_FETCH' => [
			//
			'name' => '获取操作总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_FETCH'
		],
		'MIN_TIMER_FETCH' => [
			//
			'name' => '获取操作最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_FETCH'
		],
		'AVG_TIMER_FETCH' => [
			//
			'name' => '获取操作平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_FETCH'
		],
		'MAX_TIMER_FETCH' => [
			//
			'name' => '获取操作最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_FETCH'
		],
		'COUNT_INSERT' => [
			//These columns aggregate all insert operations.
			'name' => '插入操作总数',
			'desc' => '这些列聚合了所有插入操作。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_INSERT' => [
			//
			'name' => '插入操作总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_INSERT'
		],
		'MIN_TIMER_INSERT' => [
			//
			'name' => '插入操作最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_INSERT'
		],
		'AVG_TIMER_INSERT' => [
			//
			'name' => '插入操作平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_INSERT'
		],
		'MAX_TIMER_INSERT' => [
			//
			'name' => '插入操作最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_INSERT'
		],
		'COUNT_UPDATE' => [
			//These columns aggregate all update operations.
			'name' => '更新操作次数',
			'desc' => '这些列聚合了所有更新操作。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_UPDATE' => [
			//
			'name' => '更新操作总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_UPDATE'
		],
		'MIN_TIMER_UPDATE' => [
			//
			'name' => '更新操作最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_UPDATE'
		],
		'AVG_TIMER_UPDATE' => [
			//
			'name' => '更新操作平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_UPDATE'
		],
		'MAX_TIMER_UPDATE' => [
			//
			'name' => '更新操作最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_UPDATE'
		],
		'COUNT_DELETE' => [
			//These columns aggregate all delete operations.
			'name' => '删除操作次数',
			'desc' => '这些列聚合了所有的删除操作。',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => ''
		],
		'SUM_TIMER_DELETE' => [
			//
			'name' => '删除操作总耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_DELETE'
		],
		'MIN_TIMER_DELETE' => [
			//
			'name' => '删除操作最小耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_DELETE'
		],
		'AVG_TIMER_DELETE' => [
			//
			'name' => '删除操作平均耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_DELETE'
		],
		'MAX_TIMER_DELETE' => [
			//
			'name' => '删除操作最大耗时',
			'desc' => '',
			'descInvUrl' => '',
			'link' => '',
			'linkDesc' => 'COUNT_DELETE'
		],
	]
];